version: '3.8'
services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY}
#      - JWT_SECRET=${JWT_SECRET}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#    depends_on:
#      - db

  db:
    image: postgres:15
    container_name: bankdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpassword
      POSTGRES_DB: bankdb