spring:
  application:
    name: bank-rest-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate # We use Liquibase for DDL
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  


# Security Configuration
app:
  security:
    # 32-byte (256-bit) AES Key in Base64.
    # Generated for dev: echo -n "12345678901234567890123456789012" | base64
    encryption-key: ${APP_ENCRYPTION_KEY:}
    jwt:
      secret: ${JWT_SECRET:}
      expiration-ms: 86400000 # 1 day

